[config]
media_path = "./media"
api_key = "API_KEY_GOES_HERE"

[extensions]
image = ["jpg", "jpeg", "png", "gif", "bmp", "webp"]
video = ["mp4", "mov", "avi", "mkv", "wmv", "webm"]
audio = ["mp3", "wav", "flac", "wma", "ogg"]
